default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: coolghostsdev
  username: coolghosts
  password: Lorem123
  host: localhost

test:
  <<: *default

production:
  <<: *default
  database: dbvhvkf0nmsr5d
  username: vnatjvxjsjglvp
  password: ZKNu2YvJ-sWJkX6_Qh9gvDVsMW
  host: ec2-54-247-170-228.eu-west-1.compute.amazonaws.com
